Repository GospelAid/badiup, pull requests merged in 2020-03, with the labels that each got.

#131 implemented order detail page for admin
  lib/colors.dart
  lib/models/address_model.dart
  lib/models/customer_model.dart
  lib/models/order_model.dart
  lib/screens/admin_home_page.dart
  lib/screens/admin_order_detail_page.dart
  lib/screens/cart_page.dart
  lib/widgets/order_list.dart
  lib/widgets/shipping_address_input_form.dart
  pubspec.lock
  pubspec.yaml
Labels: admin-user

#139 Settings Page
  lib/models/user_setting_model.dart
  lib/screens/settings_page.dart
  lib/sign_in.dart
  lib/widgets/admin_settings_listing.dart
  lib/widgets/main_menu.dart
  pubspec.lock
Labels: admin-user, enhancement

#158 Added Payment Method
  ios/Podfile
  ios/Podfile.lock
  lib/screens/cart_page.dart
  lib/widgets/shipping_address_input_form.dart
  pubspec.lock
  pubspec.yaml
Labels: customer-user, enhancement

#164 Disable "-" button when quantity = 1
  lib/widgets/quantity_selector.dart
Labels: customer-user

#160 Removed quantity selector from product detail page
  lib/screens/customer_product_detail_page.dart
Labels: customer-user

#174 Added quantity only option
  lib/models/stock_model.dart
  lib/screens/admin_new_product_page.dart
  lib/widgets/shipping_address_input_form.dart
Labels: needs review

#173 Removed go to cart button in product detail page
  lib/screens/customer_product_detail_page.dart
Labels: needs review

#172 Removed the publish switch in product listing
  lib/widgets/product_listing.dart
Labels: needs review

#170 When customer places an order, admin gets a push notification
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/AppDelegate.swift
  ios/Runner/Runner.entitlements
  lib/models/order_model.dart
  lib/screens/admin_home_page.dart
  lib/screens/cart_page.dart
  pubspec.lock
  pubspec.yaml
Labels: needs review

#177 Add contact-us-page and privacy-policy-page and the links to them
  lib/colors.dart
  lib/screens/about_badi_page.dart
  lib/screens/contact_us_page.dart
  lib/screens/privacy_policy_page.dart
  lib/utilities.dart
  lib/widgets/banner_button.dart
  lib/widgets/main_menu.dart
Labels: needs revision

#179 Fixed quantity selector bug
  lib/screens/cart_page.dart
Labels: needs review

#175 Fix for small crop image issue
  ios/Podfile.lock
  lib/screens/admin_new_product_page.dart
  lib/widgets/product_detail.dart
  lib/widgets/product_listing.dart
Labels: needs review

#183 Added My Orders page in Customer view
  assets/about_badi_model.JPG
  assets/about_badi_model.png
  lib/screens/about_badi_page.dart
  lib/screens/customer_order_listing_page.dart
  lib/widgets/main_menu.dart
  lib/widgets/order_list.dart
Labels: needs review

#186 Removed "show / hide stock" button
  ios/Podfile.lock
  lib/screens/admin_new_product_page.dart
Labels: needs review

#192 Fixed bug in order listing filters
  lib/screens/admin_home_page.dart
  lib/widgets/order_list.dart
Labels: needs review

#199 newly dispatched order should be placed as the first one in the 発送済み list
  lib/models/order_model.dart
  lib/screens/admin_order_detail_page.dart
  lib/widgets/order_list.dart
Labels: needs revision

#197 Remove prefixes
  lib/screens/customer_product_detail_page.dart
  lib/widgets/stock_selector.dart
Labels: needs revision

#198 Update the list of colors and sizes (#176)
  lib/models/stock_model.dart
Labels: draft

#200 Added tracking details to order
  lib/models/order_model.dart
  lib/models/tracking_details.dart
  lib/screens/admin_order_detail_page.dart
  lib/screens/admin_order_tracking_page.dart
  lib/widgets/order_list.dart
Labels: needs review
